export enum USER_ACTION_TYPES {
  SET_CURRENT_USER = "user/SET_CURRENT_USER",
}

// export enum USER_ACTION_TYPES {
//   SET_CURRENT_USER_START = "user/SET_CURRENT_USER_START",
//   SET_CURRENT_USER_SUCCESS = "user/SET_CURRENT_USER_SUCCESS",
//   SET_CURRENT_USER_FAILED = "user/SET_CURRENT_USER_FAILED",
// }
