export const CATEGORIES_ACTION_TYPES = {
  FETCH_CATEGORIES_DATA_START: "category/SET_CATEGORIES_DATA_START",
  FETCH_CATEGORIES_DATA_SUCCESS: "category/SET_CATEGORIES_DATA_SUCCESS",
  FETCH_CATEGORIES_DATA_FAILED: "category/SET_CATEGORIES_DATA_FAILED",
};
